export const ERROR_CODES = {
  // General
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMITED: "RATE_LIMITED",

  // GDPR / Consent / Data Subject Rights
  CONSENT_REQUIRED: "CONSENT_REQUIRED",
  CONSENT_OUTDATED: "CONSENT_OUTDATED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  DELETION_REQUIRES_PASSWORD: "DELETION_REQUIRES_PASSWORD",
  EXPORT_IN_PROGRESS: "EXPORT_IN_PROGRESS",

  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  PASSWORD_NOT_SET: "PASSWORD_NOT_SET",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_REUSE_DETECTED: "REFRESH_TOKEN_REUSE_DETECTED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  VERIFICATION_CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",
  VERIFICATION_CODE_INVALID: "VERIFICATION_CODE_INVALID",
  VERIFICATION_CODE_INVALIDATED: "VERIFICATION_CODE_INVALIDATED",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  RESET_CODE_EXPIRED: "RESET_CODE_EXPIRED",
  RESET_CODE_INVALID: "RESET_CODE_INVALID",
  RESET_CODE_INVALIDATED: "RESET_CODE_INVALIDATED",

  // Profile
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  UPLOAD_NOT_CONFIGURED: "UPLOAD_NOT_CONFIGURED",
  NO_FILE_UPLOADED: "NO_FILE_UPLOADED",

  // Notifications
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",

  // Background Tasks
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_ALREADY_RUNNING: "TASK_ALREADY_RUNNING",

  // Nutrition
  NUTRITION_PLAN_NOT_FOUND: "NUTRITION_PLAN_NOT_FOUND",
  NO_ACTIVE_PLAN: "NO_ACTIVE_PLAN",
  NUTRITION_PLAN_CREATING: "NUTRITION_PLAN_CREATING",
  NUTRITION_INVALID_STATUS_TRANSITION: "NUTRITION_INVALID_STATUS_TRANSITION",
  MEAL_REGENERATION_FAILED: "MEAL_REGENERATION_FAILED",
  /**
   * V2 calendar model: rejected when startDate < today, endDate < startDate,
   * or endDate > addMonths(startDate, 1).
   */
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
  // PR 5 — Notes preprocessor errors. Mapped to HTTP 400. The error
  // message is the canonical Italian text Lorenzo specified; the dashboard
  // renders it directly via PREFER_SERVER_MESSAGE_CODES in the mutation
  // error handler.
  TOO_MANY_ALLERGENS: "TOO_MANY_ALLERGENS",
  DIET_CONFLICT: "DIET_CONFLICT",

  // Credits
  INSUFFICIENT_CREDITS: "INSUFFICIENT_CREDITS",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  DEFAULT_PLAN_MISSING: "DEFAULT_PLAN_MISSING",
  NUTRITION_PLAN_NOT_READY: "NUTRITION_PLAN_NOT_READY",

  // Courses
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  ALREADY_ENROLLED: "ALREADY_ENROLLED",
  NOT_ENROLLED: "NOT_ENROLLED",
  COURSE_NOT_COMPLETED: "COURSE_NOT_COMPLETED",
  COURSE_REQUIRES_PURCHASE: "COURSE_REQUIRES_PURCHASE",

  // Events
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  ALREADY_REGISTERED: "ALREADY_REGISTERED",
  NOT_REGISTERED: "NOT_REGISTERED",
  EVENT_FULL: "EVENT_FULL",
  EVENT_PAST: "EVENT_PAST",
  EVENT_REQUIRES_PURCHASE: "EVENT_REQUIRES_PURCHASE",
  EVENT_BUNDLE_ONLY: "EVENT_BUNDLE_ONLY",
  EVENT_CANCELLED: "EVENT_CANCELLED",
  EVENT_NOT_PUBLISHED: "EVENT_NOT_PUBLISHED",
  OVERLAPPING_PURCHASE: "OVERLAPPING_PURCHASE",

  // Bundles
  BUNDLE_NOT_FOUND: "BUNDLE_NOT_FOUND",
  BUNDLE_CANCELLED: "BUNDLE_CANCELLED",
  BUNDLE_NOT_PUBLISHED: "BUNDLE_NOT_PUBLISHED",
  BUNDLE_REQUIRES_PURCHASE: "BUNDLE_REQUIRES_PURCHASE",
  BUNDLE_FREE_NOT_GRANTABLE: "BUNDLE_FREE_NOT_GRANTABLE",
  ALREADY_PURCHASED_BUNDLE: "ALREADY_PURCHASED_BUNDLE",

  // Speakers
  SPEAKER_NOT_FOUND: "SPEAKER_NOT_FOUND",
  SPEAKER_HAS_REFERENCES: "SPEAKER_HAS_REFERENCES",

  // Admin Events / Bundles
  EVENT_HAS_REGISTRATIONS: "EVENT_HAS_REGISTRATIONS",
  EVENT_HAS_PURCHASES: "EVENT_HAS_PURCHASES",
  BUNDLE_HAS_PURCHASES: "BUNDLE_HAS_PURCHASES",
  REGISTRATION_NOT_FOUND: "REGISTRATION_NOT_FOUND",
  SLUG_TAKEN: "SLUG_TAKEN",
  EVENT_IMAGE_NOT_FOUND: "EVENT_IMAGE_NOT_FOUND",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",

  // Appointments
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
  DOCTOR_NOT_FOUND: "DOCTOR_NOT_FOUND",
  DOCTOR_UNAVAILABLE: "DOCTOR_UNAVAILABLE",
  APPOINTMENT_CANNOT_CANCEL: "APPOINTMENT_CANNOT_CANCEL",

  // Professional
  PROFESSIONAL_PROFILE_NOT_FOUND: "PROFESSIONAL_PROFILE_NOT_FOUND",
  ROLE_FORBIDDEN: "ROLE_FORBIDDEN",

  // Invites
  INVITE_NOT_FOUND: "INVITE_NOT_FOUND",
  INVITE_EXPIRED: "INVITE_EXPIRED",
  INVITE_ALREADY_USED: "INVITE_ALREADY_USED",
  ADMIN_SECRET_INVALID: "ADMIN_SECRET_INVALID",

  // Patient Records
  PATIENT_RECORD_NOT_FOUND: "PATIENT_RECORD_NOT_FOUND",
  PATIENT_RECORD_HAS_VISITS: "PATIENT_RECORD_HAS_VISITS",
  PATIENT_ALREADY_LINKED: "PATIENT_ALREADY_LINKED",

  // Visits
  VISIT_NOT_FOUND: "VISIT_NOT_FOUND",

  // Locations
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  LOCATION_HAS_SLOTS: "LOCATION_HAS_SLOTS",
  LOCATION_REQUIRED: "LOCATION_REQUIRED",

  // Availability
  AVAILABILITY_CONFLICT: "AVAILABILITY_CONFLICT",

  // Chat
  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  CONVERSATION_NOT_OWNED: "CONVERSATION_NOT_OWNED",

  // Patient Data
  PATIENT_DATA_NOT_FOUND: "PATIENT_DATA_NOT_FOUND",

  // Suggestions
  SUGGESTION_NOT_FOUND: "SUGGESTION_NOT_FOUND",

  // Blog
  BLOG_POST_NOT_FOUND: "BLOG_POST_NOT_FOUND",

  // Prevy
  PREVY_PRODUCT_NOT_FOUND: "PREVY_PRODUCT_NOT_FOUND",
  PREVY_INSUFFICIENT_DATA: "PREVY_INSUFFICIENT_DATA",
  PREVY_OFF_UNAVAILABLE: "PREVY_OFF_UNAVAILABLE",
  PREVY_ANALYSIS_FAILED: "PREVY_ANALYSIS_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
